#!/usr/bin/env bash
# ===========================================================================
# IDEA IA · Agent RAG Runtime — Day 1 Server Setup
# ---------------------------------------------------------------------------
# Idempotente. Corre en Ubuntu 22+/24+ como root. Hace:
#   1. Instala Docker + Compose plugin
#   2. Configura firewall UFW (22 SSH, 80, 443, 5678 n8n)
#   3. Crea /opt/ideaia-agent con docker-compose.yml + .env (passwords random)
#   4. Levanta 3 containers: postgres-agent (pgvector), postgres-n8n, n8n
#   5. Verifica que todo responde
# ===========================================================================

set -euo pipefail

# --- Helpers ---------------------------------------------------------------
log()  { printf "\n\033[1;34m[%s]\033[0m %s\n" "$(date +%H:%M:%S)" "$*"; }
ok()   { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m⚠\033[0m %s\n" "$*"; }
err()  { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; }

if [[ "${EUID}" -ne 0 ]]; then
  err "Este script debe correr como root. Salgo."
  exit 1
fi

PROJECT_DIR="/opt/ideaia-agent"
# Forzar IPv4: si curl no tiene -4 disponible, parsear ip addr para IPv4 pública
SERVER_IP="$(curl -4 -fsS --max-time 5 ifconfig.me 2>/dev/null || ip -4 addr show scope global | awk '/inet / {print $2}' | cut -d/ -f1 | head -1)"

log "Servidor: $(hostname) · IP detectada: ${SERVER_IP}"
log "Directorio del proyecto: ${PROJECT_DIR}"

# --- 1. Docker -------------------------------------------------------------
log "[1/5] Verificando Docker..."

if command -v docker &>/dev/null && docker compose version &>/dev/null; then
  ok "Docker ya instalado: $(docker --version)"
  ok "Compose plugin OK: $(docker compose version --short)"
else
  log "Instalando Docker via get.docker.com (1-2 min)..."
  curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  sh /tmp/get-docker.sh
  rm /tmp/get-docker.sh
  systemctl enable --now docker
  ok "Docker instalado: $(docker --version)"
  ok "Compose: $(docker compose version --short)"
fi

# --- 2. Firewall UFW -------------------------------------------------------
log "[2/5] Configurando firewall UFW..."

if ! command -v ufw &>/dev/null; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y ufw >/dev/null
fi

ufw --force default deny incoming  >/dev/null
ufw --force default allow outgoing >/dev/null
ufw allow 22/tcp   comment 'SSH'            >/dev/null
ufw allow 80/tcp   comment 'HTTP'           >/dev/null
ufw allow 443/tcp  comment 'HTTPS'          >/dev/null
ufw allow 5678/tcp comment 'n8n (temp)'     >/dev/null
ufw --force enable >/dev/null
ok "Firewall activo. Reglas:"
ufw status numbered | sed 's/^/    /'

# --- 3. Crear estructura del proyecto -------------------------------------
log "[3/5] Creando ${PROJECT_DIR}..."

mkdir -p "${PROJECT_DIR}/db-init"

# .env con passwords random (solo si no existe)
if [[ ! -f "${PROJECT_DIR}/.env" ]]; then
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  N8N_DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)

  cat > "${PROJECT_DIR}/.env" <<EOF
# Generated by setup-day1.sh on $(date -Iseconds)
# IMPORTANTE: passwords random — guardalos en tu password manager.
# Para conectarte a Postgres desde n8n usá host=postgres-agent (red Docker)
# Para conectarte desde tu Windows: ssh tunnel — vemos en Día 2.

# --- postgres-agent (DB del RAG) ---
POSTGRES_AGENT_USER=ideaia
POSTGRES_AGENT_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_AGENT_DB=ideaia_agent

# --- postgres-n8n (DB interna de n8n) ---
POSTGRES_N8N_USER=n8n
POSTGRES_N8N_PASSWORD=${N8N_DB_PASSWORD}
POSTGRES_N8N_DB=n8n

# --- n8n ---
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_HOST=${SERVER_IP}
N8N_PORT=5678
N8N_PROTOCOL=http
WEBHOOK_URL=http://${SERVER_IP}:5678/
GENERIC_TIMEZONE=America/Bogota
EOF
  chmod 600 "${PROJECT_DIR}/.env"
  ok ".env creado con passwords random (chmod 600)"
else
  ok ".env ya existe, no lo toco"
fi

# docker-compose.yml
cat > "${PROJECT_DIR}/docker-compose.yml" <<'COMPOSE'
# IDEA IA · Agent stack — gestionado por /opt/ideaia-agent
# No editar a mano (lo regenera setup-day1.sh). Cambios → vía el repo.
name: ideaia-agent

services:
  postgres-agent:
    image: pgvector/pgvector:pg16
    container_name: ideaia-postgres-agent
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_AGENT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AGENT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AGENT_DB}
    ports:
      - "127.0.0.1:5432:5432"   # solo localhost — n8n se conecta vía red interna
    volumes:
      - postgres_agent_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_AGENT_USER} -d ${POSTGRES_AGENT_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-n8n:
    image: postgres:16
    container_name: ideaia-postgres-n8n
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_N8N_USER}
      POSTGRES_PASSWORD: ${POSTGRES_N8N_PASSWORD}
      POSTGRES_DB: ${POSTGRES_N8N_DB}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_n8n_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_N8N_USER} -d ${POSTGRES_N8N_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: ideaia-n8n
    restart: unless-stopped
    depends_on:
      postgres-n8n:
        condition: service_healthy
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres-n8n
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_N8N_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_N8N_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_N8N_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_DIAGNOSTICS_ENABLED: "false"
      # Permite cookies via HTTP plano. Sacar cuando montemos HTTPS con dominio.
      N8N_SECURE_COOKIE: "false"
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_agent_data:
    name: ideaia-postgres-agent-data
  postgres_n8n_data:
    name: ideaia-postgres-n8n-data
  n8n_data:
    name: ideaia-n8n-data
COMPOSE
ok "docker-compose.yml escrito"

# Init SQL: extensiones de Postgres
cat > "${PROJECT_DIR}/db-init/01-extensions.sql" <<'SQL'
-- Extensiones cargadas al crear la base por primera vez.
-- Idempotente: usa IF NOT EXISTS.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Sanity check para los logs del container
DO $$ BEGIN
  RAISE NOTICE 'Extensions loaded: vector, pg_trgm, unaccent, uuid-ossp';
END $$;
SQL
ok "db-init/01-extensions.sql escrito (pgvector + pg_trgm + unaccent + uuid-ossp)"

# --- 4. Levantar containers ------------------------------------------------
log "[4/5] Levantando containers (docker compose up -d)..."
cd "${PROJECT_DIR}"
docker compose pull
docker compose up -d

log "Esperando que postgres-agent quede healthy..."
for i in {1..30}; do
  status=$(docker inspect -f '{{.State.Health.Status}}' ideaia-postgres-agent 2>/dev/null || echo "starting")
  if [[ "$status" == "healthy" ]]; then
    ok "postgres-agent healthy"
    break
  fi
  sleep 2
done

# --- 5. Verificación -------------------------------------------------------
log "[5/5] Verificación final..."

echo
echo "→ Containers corriendo:"
docker compose ps --format "table {{.Service}}\t{{.Status}}\t{{.Ports}}" | sed 's/^/    /'

echo
echo "→ pgvector instalado en postgres-agent:"
docker exec ideaia-postgres-agent psql -U "$(grep POSTGRES_AGENT_USER .env | cut -d= -f2)" \
  -d "$(grep POSTGRES_AGENT_DB .env | cut -d= -f2)" \
  -c "SELECT extname, extversion FROM pg_extension WHERE extname IN ('vector','pg_trgm','unaccent','uuid-ossp');" \
  | sed 's/^/    /'

echo
echo "→ n8n responde:"
sleep 5
if curl -fsS --max-time 10 "http://localhost:5678/healthz" >/dev/null 2>&1; then
  ok "n8n healthz OK → http://${SERVER_IP}:5678"
else
  warn "n8n todavía está arrancando. Probá en 30 seg: curl http://localhost:5678/healthz"
fi

echo
echo "==========================================================================="
ok "Day 1 completado."
echo "==========================================================================="
echo
echo "PRÓXIMOS PASOS:"
echo "  1. Abrí el browser: http://${SERVER_IP}:5678"
echo "     Vas a ver la pantalla de setup inicial de n8n. Creá tu cuenta admin."
echo "     Email: dev-project@ideaia.app"
echo "  2. Guardá las credenciales generadas:"
echo "       cat ${PROJECT_DIR}/.env"
echo "     (pegalas en tu password manager — son únicas, no se regeneran)"
echo "  3. Avisame y arrancamos Día 2 (schema SQL del agente)."
echo
